language: node_js
os:
  - osx
  - linux

node_js: 8

cache: yarn

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - |
    yarn
    yarn lint
    yarn test
    yarn package

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      tags: true
      branch: master
      condition: "$TRAVIS_OS_NAME == linux"

  - provider: script
    skip_cleanup: true
    script: yarn deploy -p $VSCODE_MARKETPLACE_TOKEN
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME == linux"
      branch: master
